"use client";

/**
 * <LocationPageTemplate> — shared layout for the 69 city/service
 * "location-landing" pages (`/{service}-{city}-tn/`, e.g.
 * `/chiropractic-brentwood-tn/`). Data-driven from a single
 * `LocationPageData` object (see `app/_lib/locations.ts` /
 * `app/_lib/locations.json`, generated by `scripts/extract-locations.mjs`)
 * so every page shares identical structure/styling/motion, mirroring
 * `ServicePageTemplate.tsx`'s design-system reuse (`Reveal`/`Stagger`/
 * `StaggerItem`, `surface-card`, `hover-lift`, `icon-badge`, `eyebrow`/
 * `h-display`/`h-section`, `btn-*`) so these read as a natural page-type
 * belonging to the same site, not a bolted-on landing-page generator.
 *
 * All copy is VERBATIM from the live WordPress pages. Every section below
 * (differentiators / process+reviews / extraSections / faq / distance /
 * cta) is rendered CONDITIONALLY because a few live pages are missing one
 * or more of them (see `scripts/extract-locations.mjs` header comment —
 * `neuropathy-murfreesboro-tn` is a legacy template with almost none of
 * these sections at all).
 */

import Link from "next/link";
import { Reveal, Stagger, StaggerItem } from "../motion/primitives";
import { businessInfo } from "../nav";
import { ServiceIcon } from "../services/icons";
import { FaqAccordion } from "../conditions/FaqAccordion";
import { HeroBgImage } from "../HeroBgImage";
import { heroBgForService } from "../../_lib/hero-images";
import { ALL_SERVICE_LINKS } from "../../_lib/services";
import { getAllLocationSlugs } from "../../_lib/locations";
import type { LocationListBlock, LocationPageData, LocationReview } from "../../_lib/locations";

const SERVICE_LABELS: Record<string, string> = {
  chiropractic: "Chiropractic",
  "spinal-decompression": "Spinal Decompression",
  neuropathy: "Neuropathy",
  "back-pain-relief": "Back Pain Relief",
  "auto-injuries": "Auto Injuries",
  "sports-injuries": "Sports Injuries",
  "medical-weight-loss": "Medical Weight Loss",
};

export function LocationPageTemplate({ data }: { data: LocationPageData }) {
  const serviceLabel = SERVICE_LABELS[data.service] ?? data.service;
  const serviceHref = `/${data.service}/`;
  const hasDifferentiators = data.differentiators.list.items.length > 0;
  const hasProcess = data.process.list.items.length > 0;
  const hasFaq = data.faq.items.length > 0;
  const hasCta = data.cta.paragraphs.length > 0;

  return (
    <main>
      <LocationHero data={data} serviceLabel={serviceLabel} serviceHref={serviceHref} />
      {hasDifferentiators && <DifferentiatorsSection data={data} />}
      {hasProcess && <ProcessSection data={data} />}
      {data.extraSections.map((section, i) => (
        <ExtraSection key={i} heading={section.heading} paragraphs={section.paragraphs} index={i} />
      ))}
      {hasFaq && <LocationFaqSection data={data} />}
      <LocationCta data={data} serviceLabel={serviceLabel} hasCta={hasCta} />
    </main>
  );
}

function LocationHero({
  data,
  serviceLabel,
  serviceHref,
}: {
  data: LocationPageData;
  serviceLabel: string;
  serviceHref: string;
}) {
  return (
    <section className="surface-dark relative isolate overflow-hidden pt-14 pb-10 sm:pt-20 sm:pb-12 lg:pt-28 lg:pb-16">
      <HeroBgImage src={heroBgForService(data.service)} alt="" />
      <div
        aria-hidden
        className="absolute inset-0 -z-10 opacity-80"
        style={{
          background:
            "radial-gradient(45% 45% at 85% 15%, rgba(252,143,0,0.22) 0%, transparent 60%), radial-gradient(55% 55% at 5% 95%, rgba(0,75,153,0.5) 0%, transparent 70%)",
        }}
      />
      <div className="container-content relative">
        <Reveal as="div">
          <nav aria-label="Breadcrumb" className="mb-6 flex flex-wrap items-center gap-2 text-xs text-white/60">
            <Link href="/" className="hover:text-white">
              Home
            </Link>
            <span aria-hidden>/</span>
            <Link href={serviceHref} className="hover:text-white">
              {serviceLabel}
            </Link>
            <span aria-hidden>/</span>
            <span className="text-white">{data.city}</span>
          </nav>

          <span className="icon-badge h-16 w-16 bg-white/10 text-white">
            <ServiceIcon slug={data.service} width={30} height={30} />
          </span>

          <span className="eyebrow mt-6 !text-[color:var(--color-brand-orange)] block">
            {serviceLabel} in {data.city}, TN
          </span>
          <h1 className="h-display mt-3 !text-white">{data.h1}</h1>

          {data.intro.paragraphs.map((p, i) => (
            <p
              key={i}
              className="mt-6 max-w-2xl text-lg leading-relaxed text-white/80 first:mt-6 [&:not(:first-child)]:mt-4"
              dangerouslySetInnerHTML={{ __html: p }}
            />
          ))}

          <div className="mt-8 flex flex-wrap gap-3">
            <Link href="/contact-us/" className="btn btn-primary-on-dark">
              Schedule Your Consultation
            </Link>
            <a
              href={businessInfo.phoneHref}
              className="btn btn-outline-navy !border-white/30 !text-white hover:!bg-white/10"
            >
              Call {businessInfo.phone}
            </a>
          </div>
        </Reveal>
      </div>
    </section>
  );
}

function LocationList({ list }: { list: LocationListBlock }) {
  if (list.ordered) {
    return (
      <ol className="mt-6 grid gap-4">
        {list.items.map((item, i) => (
          <li
            key={i}
            className="hover-lift surface-card flex items-start gap-4 bg-white p-5"
          >
            <span className="icon-badge mt-0.5 h-7 w-7 shrink-0 text-sm font-bold">
              {i + 1}
            </span>
            <div className="text-sm leading-relaxed text-[color:var(--color-body)]">
              {item.title && (
                <p className="font-bold text-[color:var(--color-brand-navy)]">{item.title}</p>
              )}
              <p dangerouslySetInnerHTML={{ __html: item.html }} />
            </div>
          </li>
        ))}
      </ol>
    );
  }
  return (
    <Stagger as="ul" className="mt-6 grid grid-cols-1 gap-4 sm:grid-cols-2">
      {list.items.map((item, i) => (
        <StaggerItem
          key={i}
          as="li"
          className="hover-lift surface-card flex items-start gap-3 bg-white p-4"
        >
          <span className="icon-badge mt-0.5 h-7 w-7 shrink-0">
            <svg
              width="14"
              height="14"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              aria-hidden
            >
              <path d="M20 6 9 17l-5-5" />
            </svg>
          </span>
          <div className="text-sm leading-relaxed text-[color:var(--color-body)]">
            {item.title && (
              <p className="font-bold text-[color:var(--color-brand-navy)]">{item.title}</p>
            )}
            <p dangerouslySetInnerHTML={{ __html: item.html }} />
          </div>
        </StaggerItem>
      ))}
    </Stagger>
  );
}

function DifferentiatorsSection({ data }: { data: LocationPageData }) {
  return (
    <section className="section-y bg-white">
      <div className="container-content">
        <Reveal as="div" className="text-center">
          <h2 className="h-section">{data.differentiators.heading}</h2>
        </Reveal>
        <LocationList list={data.differentiators.list} />
      </div>
    </section>
  );
}

function ReviewStars({ count }: { count: number }) {
  return (
    <div className="flex gap-0.5 text-[color:var(--color-brand-orange)]" aria-label={`${count} out of 5 stars`}>
      {Array.from({ length: 5 }).map((_, i) => (
        <svg
          key={i}
          width="14"
          height="14"
          viewBox="0 0 24 24"
          fill={i < count ? "currentColor" : "none"}
          stroke="currentColor"
          strokeWidth="1.5"
          aria-hidden
        >
          <path d="M12 2.5l2.9 6.1 6.6.8-4.9 4.5 1.3 6.6L12 17l-5.9 3.5 1.3-6.6-4.9-4.5 6.6-.8L12 2.5z" />
        </svg>
      ))}
    </div>
  );
}

function ReviewsGrid({ reviews }: { reviews: LocationReview[] }) {
  return (
    <Stagger as="ul" className="mt-8 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
      {reviews.map((review, i) => (
        <StaggerItem key={i} as="li" className="hover-lift surface-card bg-white p-5">
          <ReviewStars count={review.stars} />
          <p className="mt-3 text-sm leading-relaxed text-[color:var(--color-body)]">
            &ldquo;{review.text}&rdquo;
          </p>
          <p className="mt-3 text-xs font-bold text-[color:var(--color-brand-navy)]">
            {review.author} <span className="font-normal text-[color:var(--color-muted)]"> - {review.date}</span>
          </p>
        </StaggerItem>
      ))}
    </Stagger>
  );
}

function ProcessSection({ data }: { data: LocationPageData }) {
  return (
    <section className="section-y surface-muted">
      <div className="container-content">
        <Reveal as="div" className="text-center">
          <h2 className="h-section">{data.process.heading}</h2>
        </Reveal>
        <div className="relative mt-12">
          <span
            aria-hidden
            className="absolute left-5 top-2 bottom-2 hidden w-px bg-[color:var(--color-border)] sm:block"
          />
          <Stagger as="div" className="grid gap-8">
            {data.process.list.items.map((step, i) => (
              <StaggerItem key={i} as="article" className="relative flex gap-5 sm:gap-6">
                <span className="icon-badge relative z-10 h-11 w-11 shrink-0 bg-white text-base font-bold shadow-[var(--shadow-card)]">
                  {i + 1}
                </span>
                <div className="hover-lift surface-card flex-1 bg-white p-6">
                  {step.title && (
                    <h3 className="text-lg font-bold text-[color:var(--color-brand-navy)]">{step.title}</h3>
                  )}
                  <p
                    className="mt-2 text-sm leading-relaxed text-[color:var(--color-body)]"
                    dangerouslySetInnerHTML={{ __html: step.html }}
                  />
                </div>
              </StaggerItem>
            ))}
          </Stagger>
        </div>
        {data.process.reviews && data.process.reviews.length > 0 && (
          <div className="mt-14">
            <Reveal as="div" className="text-center">
              <span className="eyebrow">Patient Reviews</span>
              <h3 className="h-section mt-3 text-2xl">What Patients Are Saying</h3>
            </Reveal>
            <ReviewsGrid reviews={data.process.reviews} />
          </div>
        )}
      </div>
    </section>
  );
}

function ExtraSection({
  heading,
  paragraphs,
  index,
}: {
  heading: string;
  paragraphs: string[];
  index: number;
}) {
  const bg = index % 2 === 0 ? "bg-white" : "surface-muted";
  return (
    <section className={`section-y ${bg}`}>
      <div className="container-content">
        <Reveal as="div">
          {heading && <h2 className="h-section">{heading}</h2>}
          {paragraphs.map((p, i) => (
            <p
              key={i}
              className="mt-5 text-[color:var(--color-body)] leading-relaxed"
              dangerouslySetInnerHTML={{ __html: p }}
            />
          ))}
        </Reveal>
      </div>
    </section>
  );
}

function LocationFaqSection({ data }: { data: LocationPageData }) {
  return (
    <section className="section-y bg-white">
      <div className="container-content">
        <Reveal as="div" className="text-center">
          <span className="eyebrow">FAQs</span>
          <h2 className="h-section mt-3">{data.faq.heading}</h2>
        </Reveal>
        <div className="mt-10">
          <FaqAccordion faqs={data.faq.items} />
        </div>
        {data.distanceParagraphs.map((p, i) => (
          <p
            key={i}
            className="mt-8 text-center text-sm leading-relaxed text-[color:var(--color-muted)]"
            dangerouslySetInnerHTML={{ __html: p }}
          />
        ))}
      </div>
    </section>
  );
}

function LocationCta({
  data,
  serviceLabel,
  hasCta,
}: {
  data: LocationPageData;
  serviceLabel: string;
  hasCta: boolean;
}) {
  const citySlug = data.slug.slice(data.service.length + 1); // e.g. "la-vergne-tn"
  const existingSlugs = new Set(getAllLocationSlugs());
  const related = ALL_SERVICE_LINKS.filter((s) => {
    if (s.label === serviceLabel) return false;
    const otherService = s.href.replace(/\//g, "");
    return existingSlugs.has(`${otherService}-${citySlug}`);
  });

  return (
    <section className="surface-dark section-y relative overflow-hidden">
      <div
        aria-hidden
        className="absolute inset-0 -z-10 opacity-70"
        style={{
          background:
            "radial-gradient(45% 60% at 90% 20%, rgba(252,143,0,0.22) 0%, transparent 60%)",
        }}
      />
      <div className="container-content relative text-center">
        <Reveal as="div">
          <span className="eyebrow !text-[color:var(--color-brand-orange)]">Take the Next Step</span>
          <h2 className="h-section mt-3 !text-white">
            {data.cta.heading || `Ready to Get Started in ${data.city}?`}
          </h2>
          {hasCta ? (
            data.cta.paragraphs.map((p, i) => (
              <p
                key={i}
                className="mx-auto mt-4 max-w-xl text-white/80 leading-relaxed"
                dangerouslySetInnerHTML={{ __html: p }}
              />
            ))
          ) : (
            <p className="mx-auto mt-4 max-w-xl text-white/80 leading-relaxed">
              Schedule a consultation with Rutherford Spine &amp; Wellness Center in
              Murfreesboro, TN, and get a care plan built around your specific
              symptoms and goals.
            </p>
          )}

          <div className="mt-8 flex flex-wrap justify-center gap-3">
            <Link href="/contact-us/" className="btn btn-primary-on-dark">
              Schedule Your Consultation
            </Link>
            <a
              href={businessInfo.phoneHref}
              className="btn btn-outline-navy !border-white/30 !text-white hover:!bg-white/10"
            >
              Call {businessInfo.phone}
            </a>
          </div>

          {related.length > 0 && (
            <div className="mt-10 flex flex-wrap justify-center gap-2 border-t border-white/10 pt-8">
              <span className="mr-2 text-sm text-white/50">Related services in {data.city}:</span>
              {related.map((r) => (
                <Link
                  key={r.href}
                  href={`${r.href.slice(0, -1)}-${citySlug}/`}
                  className="rounded-full bg-white/10 px-4 py-1.5 text-sm font-medium text-white/90 transition-colors hover:bg-white/20"
                >
                  {r.label}
                </Link>
              ))}
            </div>
          )}
        </Reveal>
      </div>
    </section>
  );
}
