/**
 * Typed loader for the 69 city/service "location-landing" pages
 * (`/{service}-{city}-tn/`). Data itself lives in `app/_lib/locations.json`,
 * generated by `scripts/extract-locations.mjs` from already-scraped WP HTML
 * (see that script's header comment for the extraction/dedup rules).
 *
 * Every field is VERBATIM copy from the live site — only presentation is
 * new. Some sections are legitimately empty for a given slug (e.g.
 * `neuropathy-murfreesboro-tn` is an older, much shorter WP template with
 * no differentiators/process/FAQ/cta at all) — consumers must render every
 * section conditionally.
 */
import rawLocations from "./locations.json";
import { SERVICE_PAGES } from "./services";

export type LocationListItem = { title?: string; html: string };
export type LocationListBlock = { ordered: boolean; items: LocationListItem[] };
export type LocationReview = { stars: number; text: string; author: string; date: string };
export type LocationFaqItem = { question: string; answer: string };
export type LocationExtraSection = { heading: string; paragraphs: string[] };

export type LocationPageData = {
  slug: string;
  service: string;
  city: string;
  h1: string;
  intro: { heading: string; paragraphs: string[] };
  differentiators: { heading: string; list: LocationListBlock };
  process: { heading: string; list: LocationListBlock; reviews?: LocationReview[] };
  extraSections: LocationExtraSection[];
  faq: { heading: string; items: LocationFaqItem[] };
  distanceParagraphs: string[];
  cta: { heading: string; paragraphs: string[] };
};

const LOCATIONS = rawLocations as Record<string, LocationPageData>;

export function getLocationPage(slug: string): LocationPageData | undefined {
  return LOCATIONS[slug];
}

export function getAllLocationSlugs(): string[] {
  return Object.keys(LOCATIONS);
}

/** Service label + hero image + related-service links, reused from the 7
 * core service pages' own data module rather than duplicated per-location
 * (location pages have zero body images of their own). */
export function getServiceMeta(service: string) {
  return SERVICE_PAGES[service];
}
